#%RAML 1.0 NamedExample


    
  value:  
     {
   "total_items": 3,
  "items": [
    {
      "id": "ABC123",
      "quantity": 2,
      "price": "19.99",
      "state" : 0
    },
    {
      "id": "DEF456",
      "quantity": 1,
      "price": "29.99",
      "state" : 0
    },
    {
      "id": "GHI789",
      "quantity": 3,
      "price": "15.50",
      "state" : 0
    }],
    "status": "en_attente_de_validation",
    "address_source": "789 Oak St, Cityville",
    "address_destination": "101 Pine St, Villagetown",
    "owner": "John Doe",
    "create_date": "2024-04-24",
    "update_date": "2024-04-24"
     }
  