#%RAML 1.0 NamedExample

  value: |
    [{
      "ID": "1",
      "status": "en_attente_de_validation",
      "total_items": 3,
      "address": "50 av des grésillons 92600 Asnières",
      "owner": "Bahaa Guidani",
      "items": [
        {
          "id": "ABC123",
          "quantity": 2,
          "price": "19.99",
          "state" : 0
        },
        {
          "id": "DEF456",
          "quantity": 1,
          "price": "29.99",
          "state" : 0
        },
        {
          "id": "GHI789",
          "quantity": 3,
          "price": "15.50",
          "state" : 0
        }
      ],
      "create_date": "now",
      "update_date": "now"
    },   
    {
      "ID": "1",
      "status": "en_attente_de_validation",
      "total_items": 3,
      "address": "50 av des grésillons 92600 Asnières",
      "owner": "Bahaa Guidani",
      "items": [
        {
          "id": "ABC123",
          "quantity": 2,
          "price": "19.99",
          "state" : 0
        },
        {
          "id": "DEF456",
          "quantity": 1,
          "price": "29.99",
          "state" : 0
        },
        {
          "id": "GHI789",
          "quantity": 3,
          "price": "15.50",
          "state" : 0
        }
      ],
      "create_date": "now",
      "update_date": "now"
    }
    
    
        ]
